apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Huawei Cloud Vpc
  creationTimestamp: null
  labels:
    type: terraform
  name: huawei-vpc
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: |
        terraform {
          required_providers {
            huaweicloud = {
              source = "registry.terraform.io/huaweicloud/huaweicloud"
            }
          }
        }
       
        resource "huaweicloud_vpc" "vpc" {
          name = var.vpc_name
          cidr = var.vpc_cidr
        }

        resource "huaweicloud_vpc_subnet" "subnet" {
          name       = var.subnet_name
          cidr       = var.subnet_cidr
          gateway_ip = var.subnet_gateway_ip
          vpc_id     = huaweicloud_vpc.vpc.id
          availability_zone = var.availability_zone
        }

        variable "vpc_name" {
          description = "Vpc name"
          default = "test-vpc-poc"
          type = string
        }

        variable "vpc_cidr" {
          description = "Vpc CIDR block"
          default = "192.168.0.0/16"
          type = string
        }
        variable "subnet_name" {
          description = "Subnet name"
          default = "test-subnet-poc"
          type = string
        }

        variable "subnet_cidr" {
          description = "Subnet CIDR block"
          default = "192.168.0.0/21"
          type = string
        }

        variable "availability_zone" {
          description = "Availability zone"
          default = "AZ1"
          type = string
        }

        variable "subnet_gateway_ip" {
          description = "Subnet gateway ip"
          default = "192.168.0.1"
          type = string
        }
        
        output"vpc_id" {
          value = huaweicloud_vpc.vpc.id
          description = "vpc id"
        }

        output"subnet_id" {
          value = huaweicloud_vpc_subnet.subnet.id
          description = "subnet id"
        }

        output"subnet_subnet_id" {
          value = huaweicloud_vpc_subnet.subnet.subnet_id
          description = "subnet_subnet id"
        }
    
      providerRef:
        name: huawei
        namespace: default
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
